DROP TABLE IF EXISTS PET;

CREATE TABLE PET (
  PETS_ID INTEGER PRIMARY KEY NOT NULL,
  OWNERS_MOBILE_NUMBER INTEGER NOT NULL,
  OWNERS_NIF VARCHAR(10) NOT NULL,
  PETS_SPECIES VARCHAR(10) NOT NULL,
  PETS_BREED VARCHAR(100) NOT NULL,	
  PETS_DATE_OF_BIRTH VARCHAR(12) NOT NULL,
  PETS_MICROCHIP_NUMBER INTEGER NOT NULL,
  PETS_NAME VARCHAR(100) NOT NULL,
  PETS_OBSERVATIONS VARCHAR(500)
);


DROP TABLE IF EXISTS USERS;

CREATE TABLE USERS (
  USERS_ID INTEGER NOT NULL,
  USERS_NAME VARCHAR(100) NOT NULL,
  USERS_SURNAME VARCHAR(100) NOT NULL,
  USERS_EMAIL VARCHAR(100) NOT NULL,
  USERS_PASSWORD VARCHAR(100) NOT NULL,
  USERS_NIF VARCHAR(100) NOT NULL,
  USERS_MOBILE_NUMBER INTEGER NOT NULL
);
